# Reemplazar con los valores del proyecto del grupo en SonarQube Cloud.
sonar.organization=REEMPLAZAR-ORGANIZATION-KEY
sonar.projectKey=REEMPLAZAR-PROJECT-KEY

sonar.sources=src
sonar.tests=tests
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
